import { Agent, Integration, MessagingChannel } from '@/types';

export const ORSO_AGENTS: Agent[] = [
  {
    id: 'jerome',
    name: 'Jérôme',
    role: 'Credit Manager & Recouvrement',
    department: 'Trésorerie & Finance',
    avatar: '💼',
    themeColor: {
      bg: 'bg-blue-950/40',
      border: 'border-blue-700/50',
      text: 'text-blue-400',
      accent: 'bg-blue-600 hover:bg-blue-500',
      badge: 'bg-blue-900/60 text-blue-300 border-blue-700/60',
    },
    status: 'online',
    description: 'Veille sur votre trésorerie, suit la balance âgée, analyse la solvabilité de vos clients et gère vos relances sans stress.',
    quickActions: [
      { label: '📊 État de la balance âgée', prompt: 'Quelle est la situation actuelle de notre balance âgée et le total des retards ?' },
      { label: '⚠️ Retards de plus de 30 jours', prompt: 'Peux-tu me lister les factures en retard de plus de 30 jours et les actions à engager ?' },
      { label: '🔍 Vérifier un SIREN / Client', prompt: 'Je souhaite vérifier la santé financière et le scoring d’un client via son SIREN.' },
      { label: '✉️ Proposer les relances du jour', prompt: 'Quelles sont les relances prioritaires à effectuer aujourd’hui auprès de nos débiteurs ?' },
    ],
  },
  {
    id: 'lucas',
    name: 'Lucas',
    role: 'Commercial & Prospection (SDR)',
    department: 'Développement Commercial',
    avatar: '🎯',
    themeColor: {
      bg: 'bg-purple-950/40',
      border: 'border-purple-700/50',
      text: 'text-purple-400',
      accent: 'bg-purple-600 hover:bg-purple-500',
      badge: 'bg-purple-900/60 text-purple-300 border-purple-700/60',
    },
    status: 'online',
    description: 'Détecte de nouveaux prospects qualifiés, prépare vos e-mails d’approche et enrichit automatiquement votre CRM.',
    quickActions: [
      { label: '🚀 Synthèse du pipeline', prompt: 'Fais-moi un point sur l’état de notre pipeline commercial et les leads qualifiés cette semaine.' },
      { label: '🎯 Nouveaux prospects ciblés', prompt: 'Trouve et liste 5 entreprises cibles correspondant à notre client idéal dans le secteur B2B.' },
      { label: '✍️ Rédiger une approche froide', prompt: 'Rédige une proposition d’accroche personnalisée pour un dirigeant de PME industrielle.' },
    ],
  },
  {
    id: 'clara',
    name: 'Clara',
    role: 'Support Client & SAV',
    department: 'Relation Client',
    avatar: '💬',
    themeColor: {
      bg: 'bg-emerald-950/40',
      border: 'border-emerald-700/50',
      text: 'text-emerald-400',
      accent: 'bg-emerald-600 hover:bg-emerald-500',
      badge: 'bg-emerald-900/60 text-emerald-300 border-emerald-700/60',
    },
    status: 'online',
    description: 'Assiste vos clients 24/7 sur les questions courantes, suit les demandes en attente et prépare les escalades critiques.',
    quickActions: [
      { label: '🎫 Demandes en attente', prompt: 'Y a-t-il des demandes de clients non traitées ou des réclamations urgentes aujourd’hui ?' },
      { label: '💡 Suggestions d’amélioration FAQ', prompt: 'Quelles sont les 3 questions récurrentes que nos clients ont posées cette semaine ?' },
    ],
  },
  {
    id: 'victor',
    name: 'Victor',
    role: 'Spécialiste Appels d’Offres',
    department: 'Marchés Publics',
    avatar: '📜',
    themeColor: {
      bg: 'bg-amber-950/40',
      border: 'border-amber-700/50',
      text: 'text-amber-400',
      accent: 'bg-amber-600 hover:bg-amber-500',
      badge: 'bg-amber-900/60 text-amber-300 border-amber-700/60',
    },
    status: 'online',
    description: 'Veille sur le BOAMP et le TED, analyse les dossiers de consultation (DCE) et prépare vos mémoires techniques.',
    quickActions: [
      { label: '🏛️ Opportunités BOAMP du jour', prompt: 'Quels nouveaux appels d’offres correspondent à nos compétences sur notre région ?' },
      { label: '📑 Synthèse d’un DCE', prompt: 'Je t’ai déposé un cahier des charges, peux-tu m’en extraire les critères d’élimination et de notation ?' },
    ],
  },
];

export const SAMPLE_INTEGRATIONS: Integration[] = [
  {
    id: 'pennylane',
    name: 'Pennylane',
    category: 'erp',
    provider: 'Pennylane API',
    description: 'Synchronisation bidirectionnelle des factures de vente, des règlements clients et de la balance comptable.',
    status: 'disconnected',
    lastSync: 'Jamais synchronisé',
    metricLabel: 'Configuration Hermès',
    metricValue: 'Clé API non configurée',
    accountDetails: 'Requiert PENNYLANE_API_KEY',
    configKey: 'PENNYLANE_API_KEY',
  },
  {
    id: 'sellsy',
    name: 'Sellsy CRM & Factures',
    category: 'erp',
    provider: 'Sellsy v2',
    description: 'Extraction des devis signés, des factures échues et des contacts décideurs.',
    status: 'disconnected',
    lastSync: 'Jamais synchronisé',
    metricLabel: 'Configuration Hermès',
    metricValue: 'Clé API non configurée',
    accountDetails: 'Requiert SELLSY_TOKEN',
    configKey: 'SELLSY_TOKEN',
  },
  {
    id: 'odoo',
    name: 'Odoo ERP',
    category: 'erp',
    provider: 'Odoo XML-RPC',
    description: 'Module Comptabilité et Ventes pour PME.',
    status: 'disconnected',
    lastSync: 'Jamais synchronisé',
    metricLabel: 'Configuration Hermès',
    metricValue: 'Instance non paramétrée',
    accountDetails: 'Requiert ODOO_URL',
    configKey: 'ODOO_URL',
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace (Gmail)',
    category: 'mail',
    provider: 'Google OAuth',
    description: 'Envoi des relances amiables et réception des justificatifs de paiement des clients.',
    status: 'disconnected',
    lastSync: 'Jamais synchronisé',
    metricLabel: 'Messagerie',
    metricValue: 'Compte non connecté',
    accountDetails: 'Requiert OAuth Google',
    configKey: 'GOOGLE_WORKSPACE_CREDENTIALS',
  },
  {
    id: 'microsoft-365',
    name: 'Microsoft 365 (Outlook)',
    category: 'mail',
    provider: 'Graph API',
    description: 'Alternative messagerie entreprise pour l’envoi et le suivi des courriels.',
    status: 'disconnected',
    lastSync: 'Jamais synchronisé',
    metricLabel: 'Messagerie',
    metricValue: 'Compte non connecté',
    accountDetails: 'Requiert MICROSOFT_365_TOKEN',
    configKey: 'MICROSOFT_365_TOKEN',
  },
  {
    id: 'pappers',
    name: 'Pappers API & Scoring',
    category: 'legal',
    provider: 'Pappers Open Data',
    description: 'Fiche financière complète, score de défaillance, bilans et dirigeants légaux des tiers.',
    status: 'pending',
    lastSync: 'Données publiques',
    metricLabel: 'Mode Découverte',
    metricValue: 'Open Data libre (Sans clé)',
    accountDetails: 'Optionnel : PAPPERS_API_KEY',
    configKey: 'PAPPERS_API_KEY',
  },
  {
    id: 'bodacc',
    name: 'Veille Légale BODACC',
    category: 'legal',
    provider: 'DILA Open Data',
    description: 'Surveillance proactive des procédures collectives (redressements, liquidations judiciaires).',
    status: 'connected',
    lastSync: 'Temps réel',
    metricLabel: 'Compétence Hermès',
    metricValue: 'Skill actif (BODACC Open Data)',
    accountDetails: 'Flux officiel DILA',
    configKey: 'BODACC_OPEN_DATA',
  },
  {
    id: 'hubspot',
    name: 'HubSpot CRM',
    category: 'crm',
    provider: 'HubSpot API',
    description: 'Synchronisation des contacts commerciaux, création de deals et suivi des échanges.',
    status: 'disconnected',
    lastSync: 'Jamais synchronisé',
    metricLabel: 'Configuration Hermès',
    metricValue: 'Clé API non configurée',
    accountDetails: 'Requiert HUBSPOT_API_KEY',
    configKey: 'HUBSPOT_API_KEY',
  },
  {
    id: 'hermes-web-search',
    name: 'Recherche Web Hermès',
    category: 'tools',
    provider: 'Hermès Toolset',
    description: 'Outil natif de veille, recherche et extraction web autonome pour les agents.',
    status: 'connected',
    lastSync: 'Permanent',
    metricLabel: 'Moteur de recherche',
    metricValue: 'Actif (DuckDuckGo / Tavily)',
    accountDetails: 'Outil agent natif',
  },
  {
    id: 'hermes-browser',
    name: 'Navigateur Web Autonome',
    category: 'tools',
    provider: 'Playwright / Chrome',
    description: 'Navigation web autonome, lecture de portails en ligne et capture d’écrans pour les agents.',
    status: 'connected',
    lastSync: 'Permanent',
    metricLabel: 'Automatisation',
    metricValue: 'Prêt pour les agents',
    accountDetails: 'Moteur de rendu headless',
  },
];

export const SAMPLE_CHANNELS: MessagingChannel[] = [
  {
    id: 'whatsapp',
    name: 'WhatsApp Business',
    tagline: 'Liaison directe avec vos clients & tiers',
    description: 'Permet à vos agents de dialoguer directement par WhatsApp pour obtenir des confirmations de virement ou qualifier des prospects.',
    status: 'disconnected',
    connectedAccount: 'Non configuré',
    allowedUsers: [],
    stats: {
      messagesToday: 0,
      activeSessions: 0,
    },
    configKey: 'WHATSAPP_TOKEN',
    metrics: 'Requiert WHATSAPP_TOKEN',
  },
  {
    id: 'telegram',
    name: 'Telegram (Console Dirigeant)',
    tagline: 'Notifications et alertes prioritaires sur mobile',
    description: 'Votre canal direct pour recevoir les alertes BODACC urgentes, vérifier un client via /check et consulter vos chiffres sans ouvrir votre ordinateur.',
    status: 'disconnected',
    connectedAccount: 'Non configuré',
    allowedUsers: [],
    stats: {
      messagesToday: 0,
      activeSessions: 0,
    },
    configKey: 'TELEGRAM_BOT_TOKEN',
    metrics: 'Requiert TELEGRAM_BOT_TOKEN',
  },
  {
    id: 'email',
    name: 'Passerelle Email (SMTP)',
    tagline: 'Envoi automatique et suivi des réponses',
    description: 'Canal de relance et de correspondance officielle pour l’envoi des courriers, devis et justificatifs de paiement.',
    status: 'disconnected',
    connectedAccount: 'Non configuré',
    allowedUsers: [],
    stats: {
      messagesToday: 0,
      activeSessions: 0,
    },
    configKey: 'SMTP_HOST',
    metrics: 'Requiert SMTP_HOST ou RESEND_API_KEY',
  },
];

